apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: index-html
          configMap:
            name: '{{ .Chart.Name }}-html'
            defaultMode: 420  # This will mount our File to the Pod File system
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.containers.image }}:{{ .Values.containers.tag }}"
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
          volumeMounts:
            - name: index-html
              mountPath: /tmp/html  # This will mount the index.html file to the application location
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
